#ifndef Enum_h__
#define Enum_h__

enum RESOURCEID { RESOURCE_STATIC, RESOURCE_LOGO, RESOURCE_STAGE, RESOURCE_END };
enum LOADINGID  { LOADING_STAGE, LOADING_BOSS, LOADING_END };
enum EVENTID	{ NO_EVENT, DEAD_OBJ, CHANGE_SCENE , EVENT_END };
enum PLAYERSTATE { PLAYER_WALK = 3 , PLAYER_IDLE = 4, PLAYER_WARPFALL = 9, PLAYER_WARPEND = 10 , 
					PLAYER_RUN = 27, PLAYER_RESPAWN = 28, PLAYER_RECOIL = 29 , PLAYER_LAUNCH = 34 , 
					PLAYER_AFTER03 = 41, PLAYER_AFTER02 = 42, PLAYER_AFTER01 = 43, PLAYER_END };
enum ROBOTSTATE { ROBOT_SEACH = 1, ROBOT_BROKEN = 2 , ROBOT_SHOT = 6  ,ROBOT_END };
enum BOSSSTATE { BOSS_SEACH = 0, BOSS_WALK = 3, BOSS_STUNE = 4 , BOSS_RUN = 5, BOSS_ATTACK = 8 };

#endif // Enum_h__
